'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditDocument

    '''<summary>
    '''panelDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDoc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R10 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RF11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RF11 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RF12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RF12 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDocNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDelete As Global.System.Web.UI.WebControls.Button
End Class
